---
title: "The Contentious Swedes"
---

The purpose of the project is to deepen the understanding of Sweden's democratization by examining changes in
the political use of public space from 1820 to 1939. The project aims to shed light on the political use of
contentious gatherings such as public meetings, election meetings, demonstration marches in public space. The
starting point is that public meetings in Sweden in 1820 were forbidden, while they in 1939 not only were
permitted, but also that most people then had knowledge of and access to the public space to make politics.

Something had changed, what we call the repertoire of contention had assumed a modern, democratic, form.
The project is carried out by two researchers and a system developer. It will run for four years. We will work
with the Swedish National Library's corpus of digitized daily newspapers as a source for occurrences of the public,
political meetings we are interested in. The task of detecting and extracting data on these events will be
performed by a language model (BERT). The data will be entered into a database which will be analyzed
quantitatively to track changes in the repertoire of contention, both in overall terms, and in terms of which
political groups adopted different parts of the repertoire when.

The project is important as it 1) deepens our understanding of how Swedes made politics before, during and after
Sweden's democratization, and 2) it uses digital sources, methods and technologies in a pioneering, new way.

[Svenska](../about.qmd)
